name: Build and Push Docker Image

on:
  push:
    branches:
      - teste

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        env:
          ECR_REGISTRY: 490360410258.dkr.ecr.sa-east-1.amazonaws.com
          IMAGE_NAME: teste-app
      - name: Build and push Docker image
        run: |
          TAG=$(git rev-parse --short "$GITHUB_SHA")
          IMAGE_TAG="${{ github.run_number }}-${TAG}"
          docker build -t "$ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG" .
          docker push "$ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG"
          sed -i "s,image:.*,image: ${{ github.sha }}," README.md

  # deploy_compose:
  #   runs-on: self-hosted

  #   steps:
  #     - name:
